CREATE TABLE IF NOT EXISTS `rental_agreement_bookings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `booking_id` varchar(64) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `renter_name` varchar(255) NOT NULL,
  `email` varchar(320) NOT NULL,
  `phone` varchar(80) NOT NULL,
  `drivers_license` varchar(255),
  `license_state_country` varchar(255),
  `date_of_birth` varchar(64),
  `flight_number` varchar(255),
  `address` text,
  `city_state_zip` varchar(255),
  `vehicle_year_make_model` text NOT NULL,
  `color` varchar(255) NOT NULL,
  `vin` varchar(255) NOT NULL,
  `license_plate` varchar(255) NOT NULL,
  `pickup_date` varchar(64) NOT NULL,
  `pickup_time` varchar(64) NOT NULL,
  `pickup_location` text NOT NULL,
  `return_date` varchar(64) NOT NULL,
  `return_time` varchar(64) NOT NULL,
  `return_location` text NOT NULL,
  `odometer_out` int NOT NULL DEFAULT 0,
  `fuel_out` varchar(255) NOT NULL DEFAULT 'Full',
  `mileage_allowance` varchar(255),
  `daily_rate` varchar(255) NOT NULL,
  `total_days` int NOT NULL DEFAULT 1,
  `subtotal` varchar(255) NOT NULL,
  `tax` varchar(255) NOT NULL,
  `discount_applied` varchar(255),
  `total_charged` varchar(255) NOT NULL,
  `security_deposit_hold` varchar(255) NOT NULL,
  `stripe_receipt_id` varchar(255),
  `additional_driver_name` text,
  `additional_driver_dob` varchar(255),
  `additional_driver_license` varchar(255),
  `additional_driver_license_state_country` varchar(255),
  `additional_driver_phone` varchar(255),
  `additional_driver_relationship` varchar(255),
  `agreement_notes` text,
  `renter_signature_text` text,
  `signer_ip` varchar(128),
  `signed_at` timestamp NULL,
  `signed_pdf_base64` longtext,
  `signed_pdf_file_name` varchar(255),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `rental_agreement_bookings_id` PRIMARY KEY(`id`),
  CONSTRAINT `rental_agreement_bookings_booking_id_unique` UNIQUE(`booking_id`)
);
